version: 1
timezone: Asia/Seoul

data:
  exchange: binanceusdm
  market: futures
  cache_dir: data

datasets:
  - ltf: [1m, 3m, 5m]
    # HTF 조합은 1차 백테스트에서 사용하지 않도록 제거했습니다.
    # 상위봉 필터가 필요한 경우 params.yaml > overrides 에서 별도 LTF 프로필을 생성하세요.
    start: 2024-01-01
    end:   2025-09-26

walk_forward:
  train_bars: 0
  test_bars:  0
  step:       0
  min_trades: 12

report:
  out_dir: reports
  rank_by: ProfitFactor
